//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1008
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找已本地化的字符串等等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CM_Segement {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CM_Segement() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.CM_Segement", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找重写当前线程的 CurrentUICulture 
        /// 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 FBillerID 的本地化字符串。
        /// </summary>
        internal static string biller_id {
            get {
                return ResourceManager.GetString("biller_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FDate 的本地化字符串。
        /// </summary>
        internal static string bill_date {
            get {
                return ResourceManager.GetString("bill_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FSettleID 的本地化字符串。
        /// </summary>
        internal static string clear_way {
            get {
                return ResourceManager.GetString("clear_way", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FContractAmount 的本地化字符串。
        /// </summary>
        internal static string contract_amount {
            get {
                return ResourceManager.GetString("contract_amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FContractName 的本地化字符串。
        /// </summary>
        internal static string contract_name {
            get {
                return ResourceManager.GetString("contract_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FContractNo 的本地化字符串。
        /// </summary>
        internal static string contract_no {
            get {
                return ResourceManager.GetString("contract_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FAmountHKD 的本地化字符串。
        /// </summary>
        internal static string cost {
            get {
                return ResourceManager.GetString("cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FCurrencyID 的本地化字符串。
        /// </summary>
        internal static string currency_id {
            get {
                return ResourceManager.GetString("currency_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FCustomerNew 的本地化字符串。
        /// </summary>
        internal static string customer {
            get {
                return ResourceManager.GetString("customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FDebateAmount 的本地化字符串。
        /// </summary>
        internal static string debate_amount {
            get {
                return ResourceManager.GetString("debate_amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FFetchAdd 的本地化字符串。
        /// </summary>
        internal static string delivery_place {
            get {
                return ResourceManager.GetString("delivery_place", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FDepartment 的本地化字符串。
        /// </summary>
        internal static string department_id {
            get {
                return ResourceManager.GetString("department_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FBigText 的本地化字符串。
        /// </summary>
        internal static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FEmployee 的本地化字符串。
        /// </summary>
        internal static string employee_id {
            get {
                return ResourceManager.GetString("employee_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FExchangeRate 的本地化字符串。
        /// </summary>
        internal static string exchange_rate {
            get {
                return ResourceManager.GetString("exchange_rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FExplanation 的本地化字符串。
        /// </summary>
        internal static string explanation {
            get {
                return ResourceManager.GetString("explanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FFetchAdd 的本地化字符串。
        /// </summary>
        internal static string fetch_add {
            get {
                return ResourceManager.GetString("fetch_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FFetchDate 的本地化字符串。
        /// </summary>
        internal static string fetch_date {
            get {
                return ResourceManager.GetString("fetch_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FIndex 的本地化字符串。
        /// </summary>
        internal static string index_no {
            get {
                return ResourceManager.GetString("index_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FAmount3 的本地化字符串。
        /// </summary>
        internal static string invoice_amount {
            get {
                return ResourceManager.GetString("invoice_amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FOldBillNo 的本地化字符串。
        /// </summary>
        internal static string old_bill_no {
            get {
                return ResourceManager.GetString("old_bill_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FSoCompany 的本地化字符串。
        /// </summary>
        internal static string plan_firm {
            get {
                return ResourceManager.GetString("plan_firm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FProductID 的本地化字符串。
        /// </summary>
        internal static string product_id {
            get {
                return ResourceManager.GetString("product_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FProductType 的本地化字符串。
        /// </summary>
        internal static string product_type {
            get {
                return ResourceManager.GetString("product_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FQuantity 的本地化字符串。
        /// </summary>
        internal static string qty {
            get {
                return ResourceManager.GetString("qty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FTaxRate 的本地化字符串。
        /// </summary>
        internal static string tax_rate {
            get {
                return ResourceManager.GetString("tax_rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FTotalAmount 的本地化字符串。
        /// </summary>
        internal static string total_amount {
            get {
                return ResourceManager.GetString("total_amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FTotalAmountFor 的本地化字符串。
        /// </summary>
        internal static string total_amount_for {
            get {
                return ResourceManager.GetString("total_amount_for", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FBase 的本地化字符串。
        /// </summary>
        internal static string trade_type {
            get {
                return ResourceManager.GetString("trade_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FUnitID 的本地化字符串。
        /// </summary>
        internal static string unit_id {
            get {
                return ResourceManager.GetString("unit_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FZJCustomer 的本地化字符串。
        /// </summary>
        internal static string zj_customer {
            get {
                return ResourceManager.GetString("zj_customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FEndCustomer 的本地化字符串。
        /// </summary>
        internal static string zz_customer {
            get {
                return ResourceManager.GetString("zz_customer", resourceCulture);
            }
        }
    }
}
