//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1008
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找已本地化的字符串等等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MB_Segement {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MB_Segement() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.MB_Segement", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找重写当前线程的 CurrentUICulture 
        /// 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 FCashDiscount 的本地化字符串。
        /// </summary>
        internal static string cashDiscount {
            get {
                return ResourceManager.GetString("cashDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FText7 的本地化字符串。
        /// </summary>
        internal static string clearing_way {
            get {
                return ResourceManager.GetString("clearing_way", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FExplanation 的本地化字符串。
        /// </summary>
        internal static string comment {
            get {
                return ResourceManager.GetString("comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FContractName 的本地化字符串。
        /// </summary>
        internal static string contract_name {
            get {
                return ResourceManager.GetString("contract_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FCustomer 的本地化字符串。
        /// </summary>
        internal static string customer {
            get {
                return ResourceManager.GetString("customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FText6 的本地化字符串。
        /// </summary>
        internal static string delivery_place {
            get {
                return ResourceManager.GetString("delivery_place", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FDepartment 的本地化字符串。
        /// </summary>
        internal static string department {
            get {
                return ResourceManager.GetString("department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FExplanation 的本地化字符串。
        /// </summary>
        internal static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FDate1 的本地化字符串。
        /// </summary>
        internal static string dilivery_date {
            get {
                return ResourceManager.GetString("dilivery_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FEmployee 的本地化字符串。
        /// </summary>
        internal static string employee {
            get {
                return ResourceManager.GetString("employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FText4 的本地化字符串。
        /// </summary>
        internal static string final_client {
            get {
                return ResourceManager.GetString("final_client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FIndex 的本地化字符串。
        /// </summary>
        internal static string index_no {
            get {
                return ResourceManager.GetString("index_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FText5 的本地化字符串。
        /// </summary>
        internal static string order_num {
            get {
                return ResourceManager.GetString("order_num", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FText3 的本地化字符串。
        /// </summary>
        internal static string plan_firm {
            get {
                return ResourceManager.GetString("plan_firm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FPriceFor 的本地化字符串。
        /// </summary>
        internal static string price {
            get {
                return ResourceManager.GetString("price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FText1 的本地化字符串。
        /// </summary>
        internal static string product_type {
            get {
                return ResourceManager.GetString("product_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fqty 的本地化字符串。
        /// </summary>
        internal static string qty {
            get {
                return ResourceManager.GetString("qty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FText8 的本地化字符串。
        /// </summary>
        internal static string super_customer {
            get {
                return ResourceManager.GetString("super_customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FTaxRate 的本地化字符串。
        /// </summary>
        internal static string taxRate {
            get {
                return ResourceManager.GetString("taxRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FText 的本地化字符串。
        /// </summary>
        internal static string text {
            get {
                return ResourceManager.GetString("text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FTotalAmount 的本地化字符串。
        /// </summary>
        internal static string totalAmount {
            get {
                return ResourceManager.GetString("totalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FTotalAmountFor 的本地化字符串。
        /// </summary>
        internal static string totalAmountFor {
            get {
                return ResourceManager.GetString("totalAmountFor", resourceCulture);
            }
        }
    }
}
