//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1008
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sale_Order.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SO_Segement {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SO_Segement() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sale_Order.App_GlobalResources.SO_Segement", typeof(SO_Segement).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 FDeptID 的本地化字符串。
        /// </summary>
        internal static string agency {
            get {
                return ResourceManager.GetString("agency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FAuxTaxPrice 的本地化字符串。
        /// </summary>
        internal static string aux_tax_price {
            get {
                return ResourceManager.GetString("aux_tax_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FHeadSelfS0154 的本地化字符串。
        /// </summary>
        internal static string backpaper_confirm {
            get {
                return ResourceManager.GetString("backpaper_confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FCustID 的本地化字符串。
        /// </summary>
        internal static string buy_unit {
            get {
                return ResourceManager.GetString("buy_unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FMangerID 的本地化字符串。
        /// </summary>
        internal static string charger {
            get {
                return ResourceManager.GetString("charger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FSettleID 的本地化字符串。
        /// </summary>
        internal static string clearing_way {
            get {
                return ResourceManager.GetString("clearing_way", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FEmpID 的本地化字符串。
        /// </summary>
        internal static string clerk {
            get {
                return ResourceManager.GetString("clerk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FHeadSelfS0181 的本地化字符串。
        /// </summary>
        internal static string client_logo {
            get {
                return ResourceManager.GetString("client_logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fnote 的本地化字符串。
        /// </summary>
        internal static string comment {
            get {
                return ResourceManager.GetString("comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FEntrySelfS0165 的本地化字符串。
        /// </summary>
        internal static string commission {
            get {
                return ResourceManager.GetString("commission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FEntrySelfS0168 的本地化字符串。
        /// </summary>
        internal static string commission_rate {
            get {
                return ResourceManager.GetString("commission_rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FEntrySelfS0173 的本地化字符串。
        /// </summary>
        internal static string confirm_date {
            get {
                return ResourceManager.GetString("confirm_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FHeadSelfS0153 的本地化字符串。
        /// </summary>
        internal static string contract_no {
            get {
                return ResourceManager.GetString("contract_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FEntrySelfS0160 的本地化字符串。
        /// </summary>
        internal static string cost {
            get {
                return ResourceManager.GetString("cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FBillerID 的本地化字符串。
        /// </summary>
        internal static string create_user {
            get {
                return ResourceManager.GetString("create_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FCurrencyID 的本地化字符串。
        /// </summary>
        internal static string currency {
            get {
                return ResourceManager.GetString("currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FEntrySelfS0167 的本地化字符串。
        /// </summary>
        internal static string deal_price {
            get {
                return ResourceManager.GetString("deal_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FDate 的本地化字符串。
        /// </summary>
        internal static string delivery_date {
            get {
                return ResourceManager.GetString("delivery_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FFetchAdd 的本地化字符串。
        /// </summary>
        internal static string delivery_place {
            get {
                return ResourceManager.GetString("delivery_place", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FHeadSelfS0158 的本地化字符串。
        /// </summary>
        internal static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FTaxRate 的本地化字符串。
        /// </summary>
        internal static string discount_rate {
            get {
                return ResourceManager.GetString("discount_rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fentryid 的本地化字符串。
        /// </summary>
        internal static string entry_id {
            get {
                return ResourceManager.GetString("entry_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FExchangeRate 的本地化字符串。
        /// </summary>
        internal static string exchange_rate {
            get {
                return ResourceManager.GetString("exchange_rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FEntrySelfS0164 的本地化字符串。
        /// </summary>
        internal static string fee_rate {
            get {
                return ResourceManager.GetString("fee_rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FHeadSelfS0162 的本地化字符串。
        /// </summary>
        internal static string final_client {
            get {
                return ResourceManager.GetString("final_client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FEntrySelfS0166 的本地化字符串。
        /// </summary>
        internal static string MU {
            get {
                return ResourceManager.GetString("MU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fdate 的本地化字符串。
        /// </summary>
        internal static string order_date {
            get {
                return ResourceManager.GetString("order_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FBillNo 的本地化字符串。
        /// </summary>
        internal static string order_no {
            get {
                return ResourceManager.GetString("order_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FHeadSelfS0148 的本地化字符串。
        /// </summary>
        internal static string order_type {
            get {
                return ResourceManager.GetString("order_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FHeadSelfS0152 的本地化字符串。
        /// </summary>
        internal static string oversea_client {
            get {
                return ResourceManager.GetString("oversea_client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FHeadSelfS0169 的本地化字符串。
        /// </summary>
        internal static string oversea_percentage {
            get {
                return ResourceManager.GetString("oversea_percentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FHeadSelfS0150 的本地化字符串。
        /// </summary>
        internal static string plan_firm {
            get {
                return ResourceManager.GetString("plan_firm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FHeadSelfS0180 的本地化字符串。
        /// </summary>
        internal static string print_truly {
            get {
                return ResourceManager.GetString("print_truly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FHeadSelfS0157 的本地化字符串。
        /// </summary>
        internal static string produce_way {
            get {
                return ResourceManager.GetString("produce_way", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FItemID 的本地化字符串。
        /// </summary>
        internal static string product_id {
            get {
                return ResourceManager.GetString("product_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FHeadSelfS0146 的本地化字符串。
        /// </summary>
        internal static string product_type {
            get {
                return ResourceManager.GetString("product_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FHeadSelfS0147 的本地化字符串。
        /// </summary>
        internal static string product_use {
            get {
                return ResourceManager.GetString("product_use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FHeadSelfS0149 的本地化字符串。
        /// </summary>
        internal static string project_group {
            get {
                return ResourceManager.GetString("project_group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fqty 的本地化字符串。
        /// </summary>
        internal static string qty {
            get {
                return ResourceManager.GetString("qty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FEntrySelfS0175 的本地化字符串。
        /// </summary>
        internal static string quote_no {
            get {
                return ResourceManager.GetString("quote_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FSaleStyle 的本地化字符串。
        /// </summary>
        internal static string sale_way {
            get {
                return ResourceManager.GetString("sale_way", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FAdviceConsignDate 的本地化字符串。
        /// </summary>
        internal static string suggestd_delivery_date {
            get {
                return ResourceManager.GetString("suggestd_delivery_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FEntrySelfS0158 的本地化字符串。
        /// </summary>
        internal static string target_date {
            get {
                return ResourceManager.GetString("target_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 fcess 的本地化字符串。
        /// </summary>
        internal static string tax_rate {
            get {
                return ResourceManager.GetString("tax_rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FHeadSelfS0179 的本地化字符串。
        /// </summary>
        internal static string trade_type {
            get {
                return ResourceManager.GetString("trade_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FUnitID 的本地化字符串。
        /// </summary>
        internal static string unit {
            get {
                return ResourceManager.GetString("unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fprice 的本地化字符串。
        /// </summary>
        internal static string unit_Price {
            get {
                return ResourceManager.GetString("unit_Price", resourceCulture);
            }
        }
    }
}
